/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7b0e7f06e8563f32298de1
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Fragment } from "react";
import { Route, Switch } from "react-router";
import { PrivateRoute } from "./security/PrivateRoute";

// Material UI
import Paper from "@material-ui/core/Paper";

/* START MY VIEWS IMPORT */

import ContainerEdit from "./pages/ContainerEdit";
import ContainerList from "./pages/ContainerList";
import EnvironmentEdit from "./pages/EnvironmentEdit";
import EnvironmentList from "./pages/EnvironmentList";
import ProjectEdit from "./pages/ProjectEdit";
import ProjectList from "./pages/ProjectList";
import ServiceEdit from "./pages/ServiceEdit";
import ServiceList from "./pages/ServiceList";
import UserEdit from "./pages/UserEdit";
import UserList from "./pages/UserList";
import VirtualMachineEdit from "./pages/VirtualMachineEdit";
import VirtualMachineList from "./pages/VirtualMachineList";
import VolumeEdit from "./pages/VolumeEdit";
import VolumeList from "./pages/VolumeList";

/* END MY VIEWS IMPORT */

// CUSTOM VIEWS
import Login from "./pages/Login";
import Home from "./pages/Home";
import Profile from "./pages/Profile";
import UserEdit from "./pages/UserEdit";
import UserList from "./pages/UserList";

class Routes extends Component {
  render() {
    return (
      <Switch>
        <Fragment>
          <Paper>
            <div className="main-cointainer">
              <Route exact path="/login" component={Login} />
              <PrivateRoute exact path="/" component={Home} />
              <PrivateRoute exact path="/profile" component={Profile} />
              <PrivateRoute exact path="/users/:id" component={UserEdit} roles={["ADMIN"]}/>
              <PrivateRoute exact path="/users" component={UserList} roles={["ADMIN"]}/>
              
              {/* CUSTOM VIEWS */}

              <PrivateRoute exact path="/home" component={Home} />

              {/* START MY VIEWS */}

              <PrivateRoute exact path="/containers/:id" component={ ContainerEdit }  />
              <PrivateRoute exact path="/containers" component={ ContainerList }  />
              <PrivateRoute exact path="/environments/:id" component={ EnvironmentEdit }  />
              <PrivateRoute exact path="/environments" component={ EnvironmentList }  />
              <PrivateRoute exact path="/projects/:id" component={ ProjectEdit }  />
              <PrivateRoute exact path="/projects" component={ ProjectList }  />
              <PrivateRoute exact path="/services/:id" component={ ServiceEdit }  />
              <PrivateRoute exact path="/services" component={ ServiceList }  />
              <PrivateRoute exact path="/users/:id" component={ UserEdit }  />
              <PrivateRoute exact path="/users" component={ UserList }  />
              <PrivateRoute exact path="/virtualmachines/:id" component={ VirtualMachineEdit }  />
              <PrivateRoute exact path="/virtualmachines" component={ VirtualMachineList }  />
              <PrivateRoute exact path="/volumes/:id" component={ VolumeEdit }  />
              <PrivateRoute exact path="/volumes" component={ VolumeList }  />

             {/* END MY VIEWS */}

            </div>
          </Paper>
        </Fragment>
      </Switch>
    );
  }
}

export default Routes;