/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7b0e7f06e8563f32298de1
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import DialogDelete from "../components/DialogDelete";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import Button from "@material-ui/core/Button";
// import Table from "@material-ui/core/Table";
// import TableBody from "@material-ui/core/TableBody";
// import TableCell from "@material-ui/core/TableCell";
// import TableHead from "@material-ui/core/TableHead";
// import TableRow from "@material-ui/core/TableRow";

// Table
import EnhancedTable from "../components/EnhancedTable";

// Custom Actions


// START IMPORT ACTIONS
import ContainerActions from "../redux/actions/ContainerActions";

// END IMPORT ACTIONS

/** APIs

* actionsContainer.delete
*	@description CRUD ACTION delete
*	@param ObjectId id - Id
*
* actionsContainer.list
*	@description CRUD ACTION list
*

**/


class ContainerList extends Component {
  // Init component
  constructor(props) {
    super(props);
    this.state = {
      openDialogDelete: false
    };
  }

  // Load data on start
  componentWillMount() {
    this.props.actionsContainer.loadContainerList();
  }

  // Delete data
  delete(id) {
    this.setState({ openDialogDelete: true, idDelete: id });
  }

  closeDialogDelete() {
    this.setState({ openDialogDelete: false, idDelete: null });
  }

  confirmDialogDelete(id) {
    this.props.actionsContainer.deleteContainer(this.state.idDelete).then(data => {
      this.props.actionsContainer.loadContainerList();
      this.setState({ openDialogDelete: false, idDelete: null });
    });
  }

  // Show content
  render() {
    const columns = [ 
      {
        id: "Disk",
        type: "number",
        label: "Disk"
      }, 
      {
        id: "HostName",
        type: "string",
        label: "HostName"
      }, 
      {
        id: "Memory",
        type: "number",
        label: "Memory"
      }, 
      {
        id: "Networks",
        type: "string",
        label: "Networks"
      }, 
      {
        id: "OS",
        type: "string",
        label: "OS"
      }, 
      {
        id: "ServiceEndpoints",
        type: "string",
        label: "ServiceEndpoints"
      }, 
      {
        id: "Type",
        type: "string",
        label: "Type"
      }, 
      {
        id: "UserData",
        type: "string",
        label: "UserData"
      }, 
      {
        id: "Volumes",
        type: "string",
        label: "Volumes"
      },
    ];
    const link = "/containers/";

    return (
      <div>
        <h1>Container List</h1>

        <EnhancedTable
          data={this.props.list}
          columns={columns}
          link={link}
          onDelete={this.delete.bind(this)}
        />

        <DialogDelete
          open={this.state.openDialogDelete}
          onClose={this.closeDialogDelete.bind(this)}
          onConfirm={this.confirmDialogDelete.bind(this)}
        />

        {/*
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>ID</TableCell>
              <TableCell align="right">Disk</TableCell>
              <TableCell align="right">HostName</TableCell>
              <TableCell align="right">Memory</TableCell>
              <TableCell align="right">Networks</TableCell>
              <TableCell align="right">OS</TableCell>
              <TableCell align="right">ServiceEndpoints</TableCell>
              <TableCell align="right">Type</TableCell>
              <TableCell align="right">UserData</TableCell>
              <TableCell align="right">Volumes</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {this.props.list.map(row => (
              <TableRow key={row._id}>
                <TableCell component="th" scope="row">
                  <Link to={"/containers/" + row._id} key={row._id}>
                    {row._id}
                  </Link>
                </TableCell>
                <TableCell align="right">{ row.Disk }</TableCell>
                <TableCell align="right">{ row.HostName }</TableCell>
                <TableCell align="right">{ row.Memory }</TableCell>
                <TableCell align="right">{ row.Networks }</TableCell>
                <TableCell align="right">{ row.OS }</TableCell>
                <TableCell align="right">{ row.ServiceEndpoints }</TableCell>
                <TableCell align="right">{ row.Type }</TableCell>
                <TableCell align="right">{ row.UserData }</TableCell>
                <TableCell align="right">{ row.Volumes }</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
        */}

        <div className="footer-card">
          <Link to="/containers/new">
            <Button variant="contained" color="primary">
              Add
            </Button>
          </Link>
        </div>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsContainer: bindActionCreators(ContainerActions, dispatch),
  };
};

// Validate types
ContainerList.propTypes = { 
  actionsContainer: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    list: state.ContainerListReducer.listContainer
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(ContainerList);
