/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7b0e7f06e8563f32298de1
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";

// Custom Actions


// START IMPORT ACTIONS
import ContainerActions from "../redux/actions/ContainerActions";
import EnvironmentActions from "../redux/actions/EnvironmentActions";

// END IMPORT ACTIONS

/** APIs

* actionsContainer.create
*	@description CRUD ACTION create
*
* actionsContainer.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsContainer.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsEnvironment.list
*	@description CRUD ACTION list
*

**/

class ContainerEdit extends Component {
  // Init container
  constructor(props) {
    super(props);
    this.state = {
      container: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsContainer.loadContainer(this.props.match.params.id);
    }
    
    this.props.actionsEnvironment.loadEnvironmentList();
  }

  // Insert props container in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      container: props.container
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.container._id) {
      this.props.actionsContainer.saveContainer(this.state.container).then(data => {
        this.props.history.push("/containers/");
      });
    } else {
      this.props.actionsContainer.createContainer(this.state.container).then(data => {
        this.props.history.push("/containers/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Container Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="Disk"
            label="Disk"
            value={this.state.container.Disk || ""}
            onChange={Utils.handleChange.bind(this, "container")}
            type="number"
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="HostName"
            label="HostName"
            value={this.state.container.HostName || ""}
            onChange={Utils.handleChange.bind(this, "container")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="Memory"
            label="Memory"
            value={this.state.container.Memory || ""}
            onChange={Utils.handleChange.bind(this, "container")}
            type="number"
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="Networks"
            label="Networks"
            value={this.state.container.Networks || ""}
            onChange={Utils.handleChange.bind(this, "container")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="OS"
            label="OS"
            value={this.state.container.OS || ""}
            onChange={Utils.handleChange.bind(this, "container")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="ServiceEndpoints"
            label="ServiceEndpoints"
            value={this.state.container.ServiceEndpoints || ""}
            onChange={Utils.handleChange.bind(this, "container")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="Type"
            label="Type"
            value={this.state.container.Type || ""}
            onChange={Utils.handleChange.bind(this, "container")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="UserData"
            label="UserData"
            value={this.state.container.UserData || ""}
            onChange={Utils.handleChange.bind(this, "container")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="Volumes"
            label="Volumes"
            value={this.state.container.Volumes || ""}
            onChange={Utils.handleChange.bind(this, "container")}
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation 1:m environments with Environment */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="environments">
              Environments
            </InputLabel>
            <Select
              value={this.state.container.environments || ""}
              onChange={Utils.handleChangeSelect.bind(this, "container")}
              inputProps={{
                id: "environments",
                name: "environments"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listEnvironment && this.props.listEnvironment.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/containers/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsContainer: bindActionCreators(ContainerActions, dispatch),
    actionsEnvironment: bindActionCreators(EnvironmentActions, dispatch),
  };
};

// Validate types
ContainerEdit.propTypes = { 
  actionsContainer: PropTypes.object.isRequired,
  actionsEnvironment: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    container: state.ContainerEditReducer.container,
    listEnvironment: state.ContainerEditReducer.listEnvironment
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(ContainerEdit);
