/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7b0e7f06e8563f32298de1
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";
import Switch from "@material-ui/core/Switch";
import FormControlLabel from "@material-ui/core/FormControlLabel";

// Custom Actions


// START IMPORT ACTIONS
import ServiceActions from "../redux/actions/ServiceActions";
import VolumeActions from "../redux/actions/VolumeActions";
import ProjectActions from "../redux/actions/ProjectActions";
import EnvironmentActions from "../redux/actions/EnvironmentActions";

// END IMPORT ACTIONS

/** APIs

* actionsService.create
*	@description CRUD ACTION create
*
* actionsService.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsService.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsVolume.list
*	@description CRUD ACTION list
*
* actionsProject.findByservices
*	@description CRUD ACTION findByservices
*	@param Objectid key - Id of model to search for
*
* actionsEnvironment.findByservices
*	@description CRUD ACTION findByservices
*	@param Objectid key - Id of model to search for
*

**/

class ServiceEdit extends Component {
  // Init service
  constructor(props) {
    super(props);
    this.state = {
      service: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsService.loadService(this.props.match.params.id);
    }
    
    this.props.actionsEnvironment.loadEnvironmentList();
  }

  // Insert props service in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      service: props.service
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.service._id) {
      this.props.actionsService.saveService(this.state.service).then(data => {
        this.props.history.push("/services/");
      });
    } else {
      this.props.actionsService.createService(this.state.service).then(data => {
        this.props.history.push("/services/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Service Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="Name"
            label="Name"
            value={this.state.service.Name || ""}
            onChange={Utils.handleChange.bind(this, "service")}
            margin="normal"
            fullWidth
          />
          
          <FormControlLabel
            control={
              <Switch
                id="Persistant"
                checked={this.state.service.Persistant || false}
                onChange={Utils.handleChangeCheck.bind(this, "service", "Persistant")}
                color="primary"
              />
            }
            label="Persistant"
            className="mt-20"
          />
          
          
          <TextField
            id="Version"
            label="Version"
            value={this.state.service.Version || ""}
            onChange={Utils.handleChange.bind(this, "service")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="Volumes"
            label="Volumes"
            value={this.state.service.Volumes || ""}
            onChange={Utils.handleChange.bind(this, "service")}
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation 1:m environments with Environment */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="environments">
              Environments
            </InputLabel>
            <Select
              value={this.state.service.environments || ""}
              onChange={Utils.handleChangeSelect.bind(this, "service")}
              inputProps={{
                id: "environments",
                name: "environments"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listEnvironment && this.props.listEnvironment.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/services/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsService: bindActionCreators(ServiceActions, dispatch),
    actionsEnvironment: bindActionCreators(EnvironmentActions, dispatch),
  };
};

// Validate types
ServiceEdit.propTypes = { 
  actionsService: PropTypes.object.isRequired,
  actionsEnvironment: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    service: state.ServiceEditReducer.service,
    listEnvironment: state.ServiceEditReducer.listEnvironment
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(ServiceEdit);
