/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7b0e7f06e8563f32298de1
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";

// Custom Actions


// START IMPORT ACTIONS
import VolumeActions from "../redux/actions/VolumeActions";
import EnvironmentActions from "../redux/actions/EnvironmentActions";

// END IMPORT ACTIONS

/** APIs

* actionsVolume.create
*	@description CRUD ACTION create
*
* actionsVolume.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsVolume.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsEnvironment.list
*	@description CRUD ACTION list
*

**/

class VolumeEdit extends Component {
  // Init volume
  constructor(props) {
    super(props);
    this.state = {
      volume: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsVolume.loadVolume(this.props.match.params.id);
    }
    
    this.props.actionsEnvironment.loadEnvironmentList();
  }

  // Insert props volume in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      volume: props.volume
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.volume._id) {
      this.props.actionsVolume.saveVolume(this.state.volume).then(data => {
        this.props.history.push("/volumes/");
      });
    } else {
      this.props.actionsVolume.createVolume(this.state.volume).then(data => {
        this.props.history.push("/volumes/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Volume Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="InternalConfig"
            label="InternalConfig"
            value={this.state.volume.InternalConfig || ""}
            onChange={Utils.handleChange.bind(this, "volume")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="MountPoints"
            label="MountPoints"
            value={this.state.volume.MountPoints || ""}
            onChange={Utils.handleChange.bind(this, "volume")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="Name"
            label="Name"
            value={this.state.volume.Name || ""}
            onChange={Utils.handleChange.bind(this, "volume")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="Size"
            label="Size"
            value={this.state.volume.Size || ""}
            onChange={Utils.handleChange.bind(this, "volume")}
            type="number"
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation 1:m environments with Environment */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="environments">
              Environments
            </InputLabel>
            <Select
              value={this.state.volume.environments || ""}
              onChange={Utils.handleChangeSelect.bind(this, "volume")}
              inputProps={{
                id: "environments",
                name: "environments"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listEnvironment && this.props.listEnvironment.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/volumes/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsVolume: bindActionCreators(VolumeActions, dispatch),
    actionsEnvironment: bindActionCreators(EnvironmentActions, dispatch),
  };
};

// Validate types
VolumeEdit.propTypes = { 
  actionsVolume: PropTypes.object.isRequired,
  actionsEnvironment: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    volume: state.VolumeEditReducer.volume,
    listEnvironment: state.VolumeEditReducer.listEnvironment
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(VolumeEdit);
