/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7b0e7f06e8563f32298de1
*
* You will get 10% discount for each one of your friends
* 
*/
import { combineReducers } from "redux";

// START IMPORT REDUCERS
import ContainerEditReducer from "./ContainerEditReducer";
import ContainerListReducer from "./ContainerListReducer";
import EnvironmentEditReducer from "./EnvironmentEditReducer";
import EnvironmentListReducer from "./EnvironmentListReducer";
import HomeReducer from "./HomeReducer";
import ProjectEditReducer from "./ProjectEditReducer";
import ProjectListReducer from "./ProjectListReducer";
import ServiceEditReducer from "./ServiceEditReducer";
import ServiceListReducer from "./ServiceListReducer";
import UserEditReducer from "./UserEditReducer";
import UserListReducer from "./UserListReducer";
import VolumeEditReducer from "./VolumeEditReducer";
import VolumeListReducer from "./VolumeListReducer";

// END IMPORT REDUCERS


// CUSTOM REDUCERS
import LoginReducer from "./LoginReducer";
import ProfileReducer from "./ProfileReducer";
import UserEditReducer from "./UserEditReducer";
import UserListReducer from "./UserListReducer";

const rootReducer = combineReducers({
  
  // INSERT HERE YOUR CUSTOM REDUCERS
  LoginReducer,
  ProfileReducer,
  UserEditReducer,
  UserListReducer,

  // START COMBINE REDUCERS
	ContainerEditReducer,
	ContainerListReducer,
	EnvironmentEditReducer,
	EnvironmentListReducer,
	HomeReducer,
	ProjectEditReducer,
	ProjectListReducer,
	ServiceEditReducer,
	ServiceListReducer,
	UserEditReducer,
	UserListReducer,
	VolumeEditReducer,
	VolumeListReducer,
 // END COMBINE REDUCERS

});

export default rootReducer;
