/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7b0e7f06e8563f32298de1
*
* You will get 10% discount for each one of your friends
* 
*/

// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// CONTAINER
export const CREATE_CONTAINER_SUCCESS = "CREATE_CONTAINER_SUCCESS";
export const DELETE_CONTAINER_SUCCESS = "DELETE_CONTAINER_SUCCESS";
export const FINDBYENVIRONMENTS_CONTAINER_SUCCESS = "FINDBYENVIRONMENTS_CONTAINER_SUCCESS";
export const GET_CONTAINER_SUCCESS = "GET_CONTAINER_SUCCESS";
export const LIST_CONTAINER_SUCCESS = "LIST_CONTAINER_SUCCESS";
export const UPDATE_CONTAINER_SUCCESS = "UPDATE_CONTAINER_SUCCESS";

// ENVIRONMENT
export const CREATE_ENVIRONMENT_SUCCESS = "CREATE_ENVIRONMENT_SUCCESS";
export const DELETE_ENVIRONMENT_SUCCESS = "DELETE_ENVIRONMENT_SUCCESS";
export const FINDBYPROJECTS_ENVIRONMENT_SUCCESS = "FINDBYPROJECTS_ENVIRONMENT_SUCCESS";
export const GET_ENVIRONMENT_SUCCESS = "GET_ENVIRONMENT_SUCCESS";
export const LIST_ENVIRONMENT_SUCCESS = "LIST_ENVIRONMENT_SUCCESS";
export const UPDATE_ENVIRONMENT_SUCCESS = "UPDATE_ENVIRONMENT_SUCCESS";

// PROJECT
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const LIST_PROJECT_SUCCESS = "LIST_PROJECT_SUCCESS";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";

// SERVICE
export const CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS";
export const DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS";
export const FINDBYENVIRONMENTS_SERVICE_SUCCESS = "FINDBYENVIRONMENTS_SERVICE_SUCCESS";
export const GET_SERVICE_SUCCESS = "GET_SERVICE_SUCCESS";
export const LIST_SERVICE_SUCCESS = "LIST_SERVICE_SUCCESS";
export const UPDATE_SERVICE_SUCCESS = "UPDATE_SERVICE_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const FINDBYPROJECTS_USER_SUCCESS = "FINDBYPROJECTS_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// VOLUME
export const CREATE_VOLUME_SUCCESS = "CREATE_VOLUME_SUCCESS";
export const DELETE_VOLUME_SUCCESS = "DELETE_VOLUME_SUCCESS";
export const FINDBYENVIRONMENTS_VOLUME_SUCCESS = "FINDBYENVIRONMENTS_VOLUME_SUCCESS";
export const GET_VOLUME_SUCCESS = "GET_VOLUME_SUCCESS";
export const LIST_VOLUME_SUCCESS = "LIST_VOLUME_SUCCESS";
export const UPDATE_VOLUME_SUCCESS = "UPDATE_VOLUME_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
